# Generated by Django 5.0.4 on 2024-05-12 13:31

import main.base_models
from main.constants import FIXER_PROVIDER_NAME
from django.db import migrations, models


def initialize_base_providers(apps, schema_editor) -> None:
    Provider = apps.get_model("broker", "Provider")

    Provider.objects.create(
        **{
            "name": FIXER_PROVIDER_NAME,
            "priority_order": 1,
        }
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=main.base_models.generate_uuid4,
                        max_length=42,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("priority_order", models.IntegerField()),
                ("timeout", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "db_table": "provider",
            },
        ),
        migrations.RunPython(initialize_base_providers),
    ]
