# Generated by Django 5.0.4 on 2024-05-09 10:20

import main.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency_exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyexchangerate",
            name="uuid",
            field=models.CharField(
                default=main.base_models.generate_uuid4,
                max_length=42,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="currencyexchangerate",
            unique_together={("source_currency", "target_currency", "valuation_date")},
        ),
    ]
